[project]
name = "gaming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
    "robotframework>=7.3.2",
]

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = "src"

